// Base de datos de universidades por división
// Fuente: NCAA, NAIA, NJCAA official member lists

export const NCAA_D1 = [
  "Air Force","Akron","Alabama","Alabama A&M","Alabama State","Albany","Alcorn State",
  "American","Appalachian State","Arizona","Arizona State","Arkansas","Arkansas-Pine Bluff",
  "Arkansas State","Army","Auburn","Austin Peay","Ball State","Baylor","Bellarmine",
  "Belmont","Bethune-Cookman","Binghamton","Boise State","Boston College","Boston University",
  "Bowling Green","Bradley","Brown","Bryant","Bucknell","Buffalo","Butler",
  "Cal Poly","Cal State Bakersfield","Cal State Fullerton","Cal State Northridge","California",
  "Campbell","Canisius","Central Arkansas","Central Connecticut State","Central Michigan",
  "Charleston Southern","Charlotte","Chicago State","Cincinnati","Clemson","Cleveland State",
  "Coastal Carolina","Colgate","College of Charleston","Colorado","Colorado State","Columbia",
  "Connecticut","Coppin State","Cornell","Creighton","Davidson","Dayton","Delaware",
  "Delaware State","Denver","DePaul","Detroit Mercy","Drake","Drexel","Duke",
  "Duquesne","East Carolina","East Tennessee State","Eastern Illinois","Eastern Kentucky",
  "Eastern Michigan","Eastern Washington","Elon","Evansville","Fairfield","Fairleigh Dickinson",
  "Florida","Florida A&M","Florida Atlantic","Florida Gulf Coast","Florida International",
  "Florida State","Fordham","Fresno State","Furman","Gardner-Webb","George Mason",
  "George Washington","Georgetown","Georgia","Georgia Southern","Georgia State","Georgia Tech",
  "Gonzaga","Grambling State","Grand Canyon","Green Bay","Hampton","Hartford",
  "Harvard","Hawaii","High Point","Hofstra","Holy Cross","Houston","Houston Baptist",
  "Howard","Idaho","Idaho State","Illinois","Illinois-Chicago","Illinois State","Incarnate Word",
  "Indiana","Indiana State","Iona","Iowa","Iowa State","IPFW","IUPUI","Jackson State",
  "Jacksonville","Jacksonville State","James Madison","Kansas","Kansas State","Kennesaw State",
  "Kent State","Kentucky","La Salle","Lafayette","Lamar","Lehigh","Liberty",
  "Lindenwood","Little Rock","Long Beach State","Long Island","Longwood","Louisiana",
  "Louisiana Monroe","Louisiana Tech","Louisville","Loyola Chicago","Loyola Maryland",
  "Loyola Marymount","LSU","Maine","Manhattan","Marist","Marquette","Marshall",
  "Maryland","Maryland-Eastern Shore","Massachusetts","McNeese State","Memphis","Mercer",
  "Miami","Miami (OH)","Michigan","Michigan State","Middle Tennessee","Milwaukee",
  "Minnesota","Mississippi State","Mississippi Valley State","Missouri","Missouri State",
  "Monmouth","Montana","Montana State","Morehead State","Morgan State","Mount St. Mary's",
  "Murray State","Navy","Nebraska","Nevada","Nevada-Las Vegas","New Hampshire",
  "New Mexico","New Mexico State","New Orleans","Niagara","Nicholls State","Norfolk State",
  "North Alabama","North Carolina","North Carolina A&T","North Carolina Central",
  "North Carolina State","North Dakota","North Dakota State","North Florida","North Texas",
  "Northeastern","Northern Arizona","Northern Colorado","Northern Illinois","Northern Iowa",
  "Northern Kentucky","Northwestern","Northwestern State","Notre Dame","Oakland",
  "Ohio","Ohio State","Oklahoma","Oklahoma State","Old Dominion","Ole Miss","Oral Roberts",
  "Oregon","Oregon State","Pacific","Penn State","Pennsylvania","Pepperdine","Pittsburgh",
  "Portland","Portland State","Prairie View A&M","Presbyterian","Princeton","Providence",
  "Purdue","Purdue Fort Wayne","Queens","Quinnipiac","Radford","Rhode Island","Rice",
  "Richmond","Rider","Robert Morris","Rutgers","Sacramento State","Saint Francis",
  "Saint Joseph's","Saint Louis","Saint Mary's","Saint Peter's","Sam Houston State",
  "Samford","San Diego","San Diego State","San Francisco","San Jose State","Santa Barbara",
  "Savannah State","Seattle U","Seton Hall","Siena","SIU Edwardsville","SMU","South Alabama",
  "South Carolina","South Carolina State","South Dakota","South Dakota State","South Florida",
  "Southeast Missouri State","Southeastern Louisiana","Southern","Southern Illinois",
  "Southern Mississippi","Southern Utah","St. Bonaventure","Stanford","Stephen F. Austin",
  "Stetson","Stony Brook","Syracuse","TCU","Temple","Tennessee","Tennessee State",
  "Tennessee Tech","Texas","Texas A&M","Texas A&M-Corpus Christi","Texas Southern",
  "Texas State","Texas Tech","The Citadel","Toledo","Towson","Troy","Tulane","Tulsa",
  "UAB","UC Davis","UC Irvine","UC Riverside","UC San Diego","UCF","UCLA","UMBC",
  "UMass Lowell","UNC Asheville","UNC Greensboro","UNC Wilmington","UNLV","USC","UT Arlington",
  "UT Martin","UT Rio Grande Valley","Utah","Utah State","Utah Valley","UTEP","UTSA",
  "Valparaiso","Vanderbilt","Vermont","Villanova","Virginia","Virginia Commonwealth",
  "Virginia Military Institute","Virginia Tech","Wagner","Wake Forest","Washington",
  "Washington State","Weber State","West Virginia","Western Carolina","Western Illinois",
  "Western Kentucky","Western Michigan","Wichita State","William & Mary","Winthrop",
  "Wisconsin","Wisconsin-Green Bay","Wisconsin-Milwaukee","Wofford","Wright State",
  "Wyoming","Xavier","Yale","Youngstown State"
].sort();

export const NCAA_D2 = [
  "Adelphi","Alabama in Huntsville","Albany State","Alderson Broaddus","American International",
  "Anderson","Angelo State","Assumption","Augustana","Barry","Bellarmine","Bemidji State",
  "Bentley","Black Hills State","Bloomsburg","Bowie State","California PA","California Baptist",
  "Cameron","Carson-Newman","Catawba","Central Missouri","Central Oklahoma","Chaminade",
  "Charleston","Chico State","Chowan","Clarion","Colorado Mesa","Colorado Mines","Colorado State-Pueblo",
  "Columbus State","Concord","Concordia Irvine","Concordia St. Paul","Converse","Davis & Elkins",
  "Delta State","Dominican","Drury","East Central","East Stroudsburg","East Texas Baptist",
  "Eastern New Mexico","Edinboro","Elizabeth City State","Emporia State","Fairmont State",
  "Fayetteville State","Ferris State","Findlay","Florida Southern","Florida Tech","Fort Hays State",
  "Fort Lewis","Francis Marion","Gannon","Georgia College","Grand Valley State","Hawaii Pacific",
  "Henderson State","Hilo","Hillsdale","Holy Family","Humboldt State","Indiana PA",
  "Indianapolis","Johnson C. Smith","Kentucky State","Kentucky Wesleyan","Kutztown",
  "Lake Erie","Lander","Le Moyne","LeMoyne-Owen","Lenoir-Rhyne","Lewis","Lincoln Memorial",
  "Livingstone","Lock Haven","Longwood","Lynn","Mars Hill","Mary","Mercyhurst","Mesa State",
  "Michigan Tech","Midwestern State","Miles","Minnesota Duluth","Minnesota State Mankato",
  "Minnesota State Moorhead","Minot State","Missouri Southern","Missouri Western","Molloy",
  "Montana State Billings","Morehouse","Mount Olive","Nebraska-Kearney","Nebraska-Omaha",
  "New Haven","New Mexico Highlands","Newman","North Alabama","North Greenville","Northeastern State",
  "Northern Michigan","Northern State","Northwest Missouri State","Northwood","Notre Dame de Namur",
  "Nova Southeastern","Nyack","Ohio Dominican","Oklahoma Christian","Ouachita Baptist",
  "Palm Beach Atlantic","Pfeiffer","Philadelphia","Pittsburg State","Post","Queens",
  "Quincy","Regis","Roberts Wesleyan","Rockhurst","Rogers State","Rollins","St. Cloud State",
  "St. Edward's","St. Leo","St. Martin's","St. Mary's","Saginaw Valley State","Salem International",
  "San Francisco State","Seattle Pacific","Shaw","Shepherd","Shippensburg","Sioux Falls",
  "Slippery Rock","South Carolina Aiken","Southern Arkansas","Southern Connecticut",
  "Southwest Baptist","Southwest Minnesota State","Southwestern Oklahoma","Stonehill",
  "Tarleton State","Texas A&M Commerce","Texas A&M International","Tiffin","Truman State",
  "Tusculum","Tuskegee","UC San Diego","Upper Iowa","Ursuline","Virginia State","Virginia Union",
  "Wayne State","West Alabama","West Chester","West Florida","West Georgia","West Liberty",
  "West Texas A&M","West Virginia State","West Virginia Wesleyan","Western Oregon","Wingate",
  "Winona State","Winston-Salem State"
].sort();

export const NCAA_D3 = [
  "Adrian","Albertus Magnus","Albion","Albright","Alfred","Allegheny","Alma","Amherst",
  "Anderson","Anna Maria","Arcadia","Augustana","Aurora","Averett","Babson","Baldwin Wallace",
  "Baptist Bible","Bates","Beloit","Benedictine","Berry","Bethel","Bishop's","Blackburn",
  "Bowdoin","Brandeis","Bridgewater","Brockport","Buena Vista","Buffalo State","Cabrini",
  "Cal Lutheran","Calvin","Capital","Carleton","Carnegie Mellon","Carroll","Carthage",
  "Case Western Reserve","Catholic","Centenary","Chapman","Christopher Newport","Claremont McKenna",
  "Clark","Coe","Colby","Colorado College","Connecticut College","Cortland","Curry",
  "Defiance","Delaware Valley","DePauw","Dickinson","Elmhurst","Elmira","Emory","Endicott",
  "Fitchburg State","Franklin","Franklin & Marshall","Fredonia","Frostburg State","Gallaudet",
  "Geneva","Gettysburg","Gordon","Goucher","Greensboro","Grove City","Guilford","Gustavus Adolphus",
  "Hamilton","Hamline","Hanover","Hardin-Simmons","Haverford","Heidelberg","Hiram","Hope",
  "Huntingdon","Illinois Wesleyan","Ithaca","John Carroll","Johns Hopkins","Kalamazoo",
  "Keene State","Kenyon","King's","Knox","La Roche","Lake Forest","Lakeland","Lawrence",
  "Lebanon Valley","Lehman","Lewis & Clark","Linfield","Loras","Luther","Lycoming",
  "MacMurray","Manchester","Marietta","Marymount","Massachusetts-Boston","McDaniel",
  "McMurry","Medaille","Messiah","Middlebury","Millikin","Mills","Millsaps","Misericordia",
  "MIT","Monmouth","Montclair State","Mount Union","Muhlenberg","Muskingum","Nebraska Wesleyan",
  "New England","New Jersey City","New York","Nichols","North Central","North Park","Oberlin",
  "Ohio Northern","Ohio Wesleyan","Otterbein","Pacific Lutheran","Piedmont","Plattsburgh",
  "Plymouth State","Pomona-Pitzer","Randolph-Macon","Ramapo","Rhodes","Ripon","Rochester",
  "Rockford","Roger Williams","Rose-Hulman","Rowan","Rutgers-Camden","Rutgers-Newark",
  "Salve Regina","Skidmore","Smith","Southern Maine","Springfield","St. John Fisher",
  "St. Lawrence","St. Norbert","St. Olaf","St. Thomas","Staten Island","Stevens","Stevenson",
  "Stockton","Susquehanna","Swarthmore","TCNJ","Texas Lutheran","Thiel","Thomas More",
  "Transylvania","Trinity","Trinity (CT)","Tufts","Union","Ursinus","Utica","Vassar",
  "Wabash","Wartburg","Washington","Washington & Jefferson","Washington & Lee","Waynesburg",
  "Wesley","Western Connecticut","Western New England","Westfield State","Westminster",
  "Whittier","Whitworth","Widener","Williams","Wilmington","Wisconsin-Eau Claire",
  "Wisconsin-La Crosse","Wisconsin-Oshkosh","Wisconsin-Platteville","Wisconsin-River Falls",
  "Wisconsin-Stevens Point","Wisconsin-Superior","Wisconsin-Whitewater","Wittenberg",
  "Worcester Polytechnic","Worcester State","York"
].sort();

export const NAIA_SCHOOLS = [
  "Aquinas","Avila","Baker","Belhaven","Benedictine","Bethel","Biola","Briar Cliff",
  "Bryan","Calumet St. Joseph","Carroll","Central Christian","Central Methodist","Chadron State",
  "Cleary","Coastal Georgia","College of Idaho","Columbia","Concordia Ann Arbor",
  "Concordia Seward","Corban","Cornerstone","Culver-Stockton","Cumberland","Dakota State",
  "Dakota Wesleyan","Davenport","Doane","Dordt","Eastern Oregon","Edward Waters","Embry-Riddle",
  "Faulkner","Friends","Georgetown College","Graceland","Grand View","Hannibal-LaGrange",
  "Harris-Stowe","Hastings","Holy Names","Huston-Tillotson","Indiana Wesleyan","Iowa Wesleyan",
  "Jarvis Christian","John Brown","Judson","Kansas Wesleyan","Keiser","Langston",
  "Lawrence Tech","Lewis-Clark State","Lindsey Wilson","Lubbock Christian","Madonna",
  "Malone","Martin Methodist","Mary Hardin-Baylor","Marian","Masters","McPherson",
  "Menlo","MidAmerica Nazarene","Midland","Midway","Missouri Baptist","Montana Western",
  "Morningside","Mount Mercy","Mount Vernon Nazarene","Northwestern Oklahoma","Northwestern",
  "Ohio Christian","Oklahoma Baptist","Oklahoma City","Oklahoma Wesleyan","Olivet Nazarene",
  "Ottawa","Ozarks","Park","Peru State","Point Loma Nazarene","Point Park","Reinhardt",
  "Rio Grande","Rocky Mountain","Saint Francis","Saint Xavier","Savannah College of Art",
  "Science & Arts Oklahoma","Siena Heights","Simpson","Southeastern","Southern Nazarene",
  "Southern Oregon","Southwest","Spring Arbor","St. Ambrose","St. Thomas","Sterling",
  "Tabor","Taylor","Texas College","Texas Wesleyan","Thomas","Tougaloo","Trinity International",
  "Union","University of Jamestown","Vanguard","Virginia Intermont","Waldorf","Wayland Baptist",
  "Webber International","William Carey","William Jewell","William Penn","Willmar","Xavier"
].sort();

export const NJCAA_SCHOOLS = [
  "Allegany","Allan Hancock","American River","Antelope Valley","Arizona Western",
  "Arkansas-Fort Smith","Barton County","Bishop State","Blinn","Brookhaven",
  "Butler County","Calhoun","Carl Albert State","Central Arizona","Chabot","Cisco",
  "Cochise","Coffeyville","Colby","College of DuPage","College of the Canyons",
  "Compton","Connors State","Copiah-Lincoln","Cowley County","Crowder","Darton State",
  "Diablo Valley","Dodge City","East Mississippi","Eastern Arizona","Eastern Oklahoma",
  "El Camino","Enterprise State","Feather River","Fort Scott","Garden City",
  "Glendale","Gloucester County","Gulf Coast State","Harford","Hinds",
  "Holmes","Howard","Hutchinson","Indian Hills","Iowa Central","Iowa Lakes",
  "Iowa Western","Jacksonville","Jones County","Kansas City Kansas","Kaskaskia",
  "Kilgore","Labette County","Laney","Laramie County","Lassen","Longview",
  "Los Angeles City","Los Angeles Harbor","Los Angeles Pierce","Los Angeles Trade-Tech",
  "Los Angeles Valley","LSU Eunice","McLennan","Mesa","Miles","Mississippi Delta",
  "Mississippi Gulf Coast","Missouri State-West Plains","Monroe","Mt. San Antonio",
  "Nassau","Navarro","New Mexico Military","Northeast Mississippi","Northeast Texas",
  "Northwest Mississippi","Odessa","Orange Coast","Palomar","Panola","Pasadena City",
  "Pearl River","Pensacola State","Phoenix","Pratt","Ranger","Reedley",
  "Riverside City","Rowan-Cabarrus","Sacramento City","San Bernardino Valley",
  "Santa Ana","Santa Barbara City","Santa Monica","Santa Rosa Junior","Scottsdale",
  "Seward County","Shelton State","Snead State","Snow","South Mountain","Southeast",
  "Southeastern Illinois","Southwest Tennessee","Southwestern","Spokane Falls",
  "State Fair Community","Sullivan County","Tallahassee","Temple","Tompkins Cortland",
  "Trinity Valley","Tulsa","Tyler Junior","Utah State Eastern","Vernon","Vincennes",
  "Walters State","Western Nebraska","Western Texas","Whatcom","William Rainey Harper",
  "Young Harris"
].sort();

export const ALL_UNIVERSITIES = {
  "NCAA D1": NCAA_D1,
  "NCAA D2": NCAA_D2,
  "NCAA D3": NCAA_D3,
  "NAIA": NAIA_SCHOOLS,
  "NJCAA": NJCAA_SCHOOLS,
};

export const getAllUniversities = () => [
  ...NCAA_D1.map(u=>({name:u, division:"NCAA D1"})),
  ...NCAA_D2.map(u=>({name:u, division:"NCAA D2"})),
  ...NCAA_D3.map(u=>({name:u, division:"NCAA D3"})),
  ...NAIA_SCHOOLS.map(u=>({name:u, division:"NAIA"})),
  ...NJCAA_SCHOOLS.map(u=>({name:u, division:"NJCAA"})),
];
