// Base de datos de programas deportivos universitarios por deporte y género
// NCAA D1, D2, D3, NAIA, NJCAA

export const SPORTS_PROGRAMS = {

  // ─── SOCCER ───────────────────────────────────────────────────────────────
  "Soccer - Men": {
    "NCAA D1": [
      "Adelphi","Air Force","Akron","Alabama","Albany","American","Appalachian State",
      "Arizona","Arizona State","Arkansas","Army","Auburn","Austin Peay","Ball State",
      "Baylor","Belmont","Boston College","Boston University","Bowling Green","Brown",
      "Bryant","Bucknell","Buffalo","Butler","Cal Poly","California","Campbell",
      "Central Arkansas","Central Michigan","Charlotte","Chicago State","Cincinnati",
      "Clemson","Coastal Carolina","Colgate","Colorado","Colorado State","Columbia",
      "Connecticut","Creighton","Davidson","Dayton","Delaware","Denver","DePaul",
      "Drexel","Duke","Duquesne","East Carolina","Eastern Illinois","Eastern Kentucky",
      "Elon","Fairfield","Florida","Florida Atlantic","Florida Gulf Coast",
      "Florida International","Florida State","Fordham","Furman","Gardner-Webb",
      "George Mason","Georgetown","Georgia","Georgia Southern","Georgia State",
      "George Washington","Gonzaga","Grand Canyon","Harvard","Hawaii","High Point",
      "Hofstra","Holy Cross","Houston","Howard","Illinois","Illinois State",
      "Indiana","Iowa","Iowa State","IUPUI","Jacksonville","Jacksonville State",
      "James Madison","Kansas","Kansas State","Kennesaw State","Kent State","Kentucky",
      "La Salle","Lafayette","Lehigh","Liberty","Lipscomb","Long Island","Longwood",
      "Louisiana","Louisville","Loyola Chicago","Loyola Marymount","LSU","Maine",
      "Manhattan","Marist","Marquette","Marshall","Maryland","Massachusetts",
      "Memphis","Mercer","Miami","Miami (OH)","Michigan","Michigan State",
      "Missouri","Monmouth","Mount St. Mary's","Navy","Nebraska","Nevada",
      "New Hampshire","New Mexico","New Mexico State","Niagara","North Carolina",
      "North Carolina State","North Dakota","North Florida","Northeastern",
      "Northern Illinois","Northwestern","Notre Dame","Oakland","Ohio",
      "Ohio State","Oklahoma","Ole Miss","Old Dominion","Oral Roberts","Oregon",
      "Oregon State","Penn State","Pennsylvania","Pepperdine","Pittsburgh",
      "Portland","Princeton","Providence","Purdue","Rhode Island","Rice",
      "Richmond","Rider","Robert Morris","Rutgers","Sacramento State","Saint Francis",
      "Saint Joseph's","Saint Louis","Saint Mary's","Sam Houston State","Samford",
      "San Diego","San Diego State","San Francisco","Santa Barbara",
      "Seattle U","Seton Hall","SMU","South Carolina","South Florida","Southern Illinois",
      "Stanford","Stetson","Syracuse","TCU","Temple","Tennessee","Texas",
      "Texas A&M","Texas State","Texas Tech","Toledo","Towson","Troy","Tulsa",
      "UC Davis","UC Irvine","UC Riverside","UCLA","UCF","UMass Lowell",
      "UNC Wilmington","UNLV","USC","Utah","Utah Valley","Vanderbilt","Vermont",
      "Villanova","Virginia","Virginia Commonwealth","Virginia Tech","Wagner",
      "Wake Forest","Washington","Washington State","West Virginia",
      "Western Kentucky","Wisconsin","Wofford","Wright State","Xavier","Yale"
    ],
    "NCAA D2": [
      "Adelphi","Alabama in Huntsville","American International","Angelo State",
      "Assumption","Augustana","Barry","Bentley","Bloomsburg","Bowie State",
      "California Baptist","Cal State LA","Cal State San Bernardino","Cameron",
      "Carson-Newman","Central Missouri","Chaminade","Charleston","Chico State",
      "Colorado Mesa","Colorado Mines","Colorado State-Pueblo","Columbus State",
      "Concordia Irvine","Concordia St. Paul","Delta State","Dominican","Drury",
      "East Stroudsburg","Eastern New Mexico","Edinboro","Emporia State",
      "Fairmont State","Ferris State","Findlay","Florida Southern","Florida Tech",
      "Fort Hays State","Fort Lewis","Francis Marion","Gannon","Georgia College",
      "Grand Canyon","Grand Valley State","Hawaii Pacific","Henderson State",
      "Hillsdale","Holy Family","Indianapolis","Indiana PA","Kutztown",
      "Le Moyne","Lenoir-Rhyne","Lewis","Lincoln Memorial","Lock Haven","Lynn",
      "Mars Hill","Mercyhurst","Michigan Tech","Midwestern State","Minnesota Duluth",
      "Minnesota State Mankato","Missouri Southern","Missouri Western","Molloy",
      "Mount Olive","Nebraska-Kearney","New Haven","Newman","North Alabama",
      "North Greenville","Northeastern State","Northern Michigan","Northern State",
      "Northwest Missouri State","Northwood","Notre Dame de Namur","Nova Southeastern",
      "Ohio Dominican","Oklahoma Christian","Palm Beach Atlantic","Pfeiffer",
      "Philadelphia","Pittsburg State","Queens","Quincy","Regis","Roberts Wesleyan",
      "Rockhurst","Rollins","Sacramento State","San Francisco State","Seattle Pacific",
      "Shepherd","Shippensburg","Sioux Falls","Slippery Rock","South Carolina Aiken",
      "Southern Arkansas","Southern Connecticut","Southwest Baptist",
      "Southwest Minnesota State","St. Cloud State","St. Edward's","St. Leo",
      "Tarleton State","Texas A&M Commerce","Tiffin","Truman State","Tusculum",
      "Upper Iowa","Virginia State","Wayne State","West Alabama","West Chester",
      "West Florida","West Georgia","West Liberty","West Texas A&M","Western Oregon",
      "Wingate","Winona State"
    ],
    "NCAA D3": [
      "Adrian","Albertus Magnus","Albion","Albright","Alfred","Allegheny","Alma",
      "Amherst","Anderson","Anna Maria","Arcadia","Augustana","Aurora","Averett",
      "Babson","Baldwin Wallace","Bates","Beloit","Benedictine","Berry","Bethel",
      "Blackburn","Bowdoin","Brandeis","Bridgewater","Brockport","Buena Vista",
      "Buffalo State","Cabrini","Cal Lutheran","Calvin","Capital","Carleton",
      "Carnegie Mellon","Carroll","Carthage","Case Western Reserve","Catholic",
      "Centenary","Chapman","Christopher Newport","Claremont McKenna","Clark",
      "Coe","Colby","Colorado College","Connecticut College","Cortland","Curry",
      "Defiance","Delaware Valley","DePauw","Dickinson","Elmhurst","Elmira",
      "Emory","Endicott","Fitchburg State","Franklin","Franklin & Marshall",
      "Fredonia","Frostburg State","Gettysburg","Gordon","Goucher","Greensboro",
      "Grove City","Guilford","Gustavus Adolphus","Hamilton","Hamline","Hanover",
      "Hardin-Simmons","Haverford","Heidelberg","Hiram","Hope","Huntingdon",
      "Illinois Wesleyan","Ithaca","John Carroll","Johns Hopkins","Kalamazoo",
      "Keene State","Kenyon","Knox","La Roche","Lake Forest","Lakeland",
      "Lawrence","Lebanon Valley","Lehman","Lewis & Clark","Linfield","Loras",
      "Luther","Lycoming","Manchester","Marietta","Marymount","MIT",
      "Massachusetts-Boston","McDaniel","McMurry","Medaille","Messiah","Middlebury",
      "Millikin","Millsaps","Misericordia","Mount Union","Muhlenberg","Muskingum",
      "Nebraska Wesleyan","New England","New Jersey City","New York","Nichols",
      "North Central","North Park","Oberlin","Ohio Northern","Ohio Wesleyan",
      "Otterbein","Pacific Lutheran","Piedmont","Plattsburgh","Plymouth State",
      "Pomona-Pitzer","Randolph-Macon","Ramapo","Rhodes","Ripon","Rochester",
      "Rockford","Roger Williams","Rose-Hulman","Rowan","Rutgers-Camden","Salve Regina",
      "Skidmore","Smith","Southern Maine","Springfield","St. John Fisher",
      "St. Lawrence","St. Norbert","St. Olaf","St. Thomas","Staten Island",
      "Stevens","Stevenson","Stockton","Susquehanna","Swarthmore","TCNJ",
      "Texas Lutheran","Thiel","Thomas More","Transylvania","Trinity","Tufts",
      "Union","Ursinus","Utica","Vassar","Wabash","Wartburg","Washington",
      "Washington & Jefferson","Washington & Lee","Waynesburg","Wesley",
      "Western Connecticut","Western New England","Westfield State","Westminster",
      "Whittier","Whitworth","Widener","Williams","Wittenberg","Worcester Polytechnic",
      "York"
    ],
    "NAIA": [
      "Aquinas","Avila","Baker","Belhaven","Bethel","Biola","Briar Cliff","Bryan",
      "Carroll","Central Methodist","Chadron State","Cleary","Coastal Georgia",
      "College of Idaho","Columbia","Concordia Ann Arbor","Concordia Seward",
      "Corban","Cornerstone","Culver-Stockton","Cumberland","Dakota State",
      "Dakota Wesleyan","Davenport","Doane","Dordt","Eastern Oregon","Embry-Riddle",
      "Faulkner","Friends","Georgetown College","Graceland","Grand View",
      "Hannibal-LaGrange","Hastings","Holy Names","Indiana Wesleyan","Iowa Wesleyan",
      "John Brown","Judson","Kansas Wesleyan","Keiser","Langston","Lawrence Tech",
      "Lewis-Clark State","Lindsey Wilson","Lubbock Christian","Madonna","Malone",
      "Mary Hardin-Baylor","Marian","McPherson","MidAmerica Nazarene","Midland",
      "Midway","Missouri Baptist","Montana Western","Morningside","Mount Mercy",
      "Mount Vernon Nazarene","Northwestern Oklahoma","Northwestern","Ohio Christian",
      "Oklahoma Baptist","Oklahoma City","Oklahoma Wesleyan","Olivet Nazarene",
      "Ottawa","Park","Peru State","Point Loma Nazarene","Point Park","Reinhardt",
      "Rio Grande","Rocky Mountain","Saint Francis","Saint Xavier","Science & Arts Oklahoma",
      "Siena Heights","Simpson","Southeastern","Southern Nazarene","Southern Oregon",
      "Spring Arbor","St. Ambrose","St. Thomas","Sterling","Tabor","Taylor",
      "Texas Wesleyan","Thomas","Trinity International","Union","University of Jamestown",
      "Vanguard","Waldorf","Wayland Baptist","Webber International","William Carey",
      "William Jewell","William Penn"
    ],
    "NJCAA": [
      "Allegany","Allan Hancock","American River","Antelope Valley","Arizona Western",
      "Barton County","Blinn","Brookhaven","Butler County","Carl Albert State",
      "Central Arizona","Chabot","Cisco","Cochise","Coffeyville","Colby",
      "College of DuPage","College of the Canyons","Compton","Connors State",
      "Copiah-Lincoln","Cowley County","Crowder","Diablo Valley","Dodge City",
      "East Mississippi","Eastern Arizona","Eastern Oklahoma","El Camino",
      "Fort Scott","Garden City","Glendale","Gulf Coast State","Harford","Hinds",
      "Holmes","Howard","Hutchinson","Indian Hills","Iowa Central","Iowa Lakes",
      "Iowa Western","Jacksonville","Jones County","Kansas City Kansas","Kilgore",
      "Labette County","Laney","Laramie County","Longview","Los Angeles City",
      "Los Angeles Harbor","Los Angeles Pierce","Los Angeles Valley","LSU Eunice",
      "McLennan","Mesa","Monroe","Mt. San Antonio","Nassau","Navarro",
      "Northeast Mississippi","Northeast Texas","Northwest Mississippi","Odessa",
      "Orange Coast","Palomar","Panola","Pasadena City","Pearl River",
      "Pensacola State","Phoenix","Pratt","Ranger","Reedley","Riverside City",
      "Sacramento City","San Bernardino Valley","Santa Ana","Santa Barbara City",
      "Santa Monica","Santa Rosa Junior","Scottsdale","Seward County",
      "Shelton State","South Mountain","Southeast","Southeastern Illinois",
      "Southwest Tennessee","Southwestern","Spokane Falls","State Fair Community",
      "Tallahassee","Temple","Trinity Valley","Tyler Junior","Vernon",
      "Vincennes","Walters State","Western Nebraska","Western Texas","Young Harris"
    ]
  },

  "Soccer - Women": {
    "NCAA D1": [
      "Air Force","Akron","Alabama","Albany","American","Appalachian State",
      "Arizona","Arizona State","Arkansas","Army","Auburn","Austin Peay",
      "Ball State","Baylor","Belmont","Boston College","Boston University",
      "Bowling Green","Brown","Bryant","Bucknell","Buffalo","Butler","Cal Poly",
      "California","Campbell","Central Arkansas","Central Michigan","Charlotte",
      "Cincinnati","Clemson","Coastal Carolina","Colgate","Colorado","Colorado State",
      "Columbia","Connecticut","Creighton","Davidson","Dayton","Delaware","Denver",
      "DePaul","Drexel","Duke","Duquesne","East Carolina","Eastern Illinois",
      "Elon","Fairfield","Florida","Florida Atlantic","Florida Gulf Coast",
      "Florida International","Florida State","Fordham","Furman","Gardner-Webb",
      "George Mason","Georgetown","Georgia","Georgia Southern","Georgia State",
      "George Washington","Gonzaga","Grand Canyon","Harvard","Hawaii","High Point",
      "Hofstra","Holy Cross","Houston","Howard","Illinois","Illinois State",
      "Indiana","Iowa","Iowa State","Jacksonville","James Madison","Kansas",
      "Kansas State","Kennesaw State","Kent State","Kentucky","La Salle","Lafayette",
      "Lehigh","Liberty","Lipscomb","Long Island","Longwood","Louisiana",
      "Louisville","Loyola Chicago","Loyola Marymount","LSU","Maine","Manhattan",
      "Marist","Marquette","Marshall","Maryland","Massachusetts","Memphis",
      "Mercer","Miami","Miami (OH)","Michigan","Michigan State","Missouri",
      "Monmouth","Mount St. Mary's","Navy","Nebraska","New Hampshire","New Mexico",
      "New Mexico State","Niagara","North Carolina","North Carolina State",
      "North Dakota","North Florida","Northeastern","Northern Illinois","Northwestern",
      "Notre Dame","Oakland","Ohio","Ohio State","Oklahoma","Ole Miss",
      "Old Dominion","Oral Roberts","Oregon","Oregon State","Penn State",
      "Pennsylvania","Pepperdine","Pittsburgh","Portland","Princeton","Providence",
      "Purdue","Rhode Island","Rice","Richmond","Rider","Robert Morris","Rutgers",
      "Sacramento State","Saint Francis","Saint Joseph's","Saint Louis","Saint Mary's",
      "Sam Houston State","Samford","San Diego","San Diego State","San Francisco",
      "Santa Barbara","Seattle U","Seton Hall","SMU","South Carolina","South Florida",
      "Southern Illinois","Stanford","Stetson","Syracuse","TCU","Temple","Tennessee",
      "Texas","Texas A&M","Texas State","Texas Tech","Toledo","Towson","Troy",
      "UC Davis","UC Irvine","UC Riverside","UCLA","UCF","UMass Lowell",
      "UNC Wilmington","UNLV","USC","Utah","Utah Valley","Vanderbilt","Vermont",
      "Villanova","Virginia","Virginia Commonwealth","Virginia Tech","Wagner",
      "Wake Forest","Washington","Washington State","West Virginia",
      "Western Kentucky","Wisconsin","Wofford","Xavier","Yale"
    ],
    "NCAA D2": [
      "Adelphi","Alabama in Huntsville","American International","Angelo State",
      "Assumption","Augustana","Barry","Bentley","Bloomsburg","California Baptist",
      "Cal State LA","Carson-Newman","Central Missouri","Charleston","Chico State",
      "Colorado Mesa","Colorado Mines","Colorado State-Pueblo","Columbus State",
      "Concordia Irvine","Concordia St. Paul","Delta State","Dominican","Drury",
      "East Stroudsburg","Eastern New Mexico","Edinboro","Emporia State",
      "Ferris State","Findlay","Florida Southern","Florida Tech","Fort Hays State",
      "Francis Marion","Gannon","Georgia College","Grand Valley State",
      "Hawaii Pacific","Henderson State","Holy Family","Indianapolis","Kutztown",
      "Le Moyne","Lenoir-Rhyne","Lewis","Lincoln Memorial","Lock Haven","Lynn",
      "Mars Hill","Mercyhurst","Michigan Tech","Midwestern State","Minnesota Duluth",
      "Minnesota State Mankato","Missouri Southern","Missouri Western","Molloy",
      "Mount Olive","Nebraska-Kearney","New Haven","Newman","North Alabama",
      "North Greenville","Northern Michigan","Northern State","Northwest Missouri State",
      "Northwood","Nova Southeastern","Ohio Dominican","Oklahoma Christian",
      "Palm Beach Atlantic","Pfeiffer","Pittsburg State","Queens","Quincy",
      "Regis","Roberts Wesleyan","Rockhurst","Rollins","San Francisco State",
      "Seattle Pacific","Shepherd","Shippensburg","Sioux Falls","Slippery Rock",
      "South Carolina Aiken","Southern Arkansas","Southern Connecticut",
      "Southwest Baptist","St. Cloud State","St. Leo","Tarleton State",
      "Texas A&M Commerce","Tiffin","Truman State","Tusculum","Upper Iowa",
      "Virginia State","Wayne State","West Alabama","West Chester","West Florida",
      "West Georgia","West Liberty","West Texas A&M","Western Oregon","Wingate","Winona State"
    ],
    "NCAA D3": [
      "Adrian","Albion","Albright","Alfred","Allegheny","Alma","Amherst",
      "Anderson","Anna Maria","Arcadia","Augustana","Aurora","Babson",
      "Baldwin Wallace","Bates","Beloit","Benedictine","Berry","Bethel",
      "Bowdoin","Brandeis","Bridgewater","Brockport","Buena Vista","Buffalo State",
      "Cabrini","Cal Lutheran","Calvin","Capital","Carleton","Carnegie Mellon",
      "Carroll","Carthage","Case Western Reserve","Catholic","Chapman",
      "Christopher Newport","Claremont McKenna","Clark","Coe","Colby",
      "Colorado College","Connecticut College","Cortland","Curry","Delaware Valley",
      "DePauw","Dickinson","Elmhurst","Elmira","Emory","Endicott",
      "Fitchburg State","Franklin","Franklin & Marshall","Fredonia","Frostburg State",
      "Gettysburg","Gordon","Goucher","Greensboro","Gustavus Adolphus","Hamilton",
      "Hamline","Hanover","Haverford","Heidelberg","Hiram","Hope","Illinois Wesleyan",
      "Ithaca","Johns Hopkins","Kalamazoo","Keene State","Kenyon","Knox",
      "La Roche","Lake Forest","Lakeland","Lawrence","Lebanon Valley","Lewis & Clark",
      "Linfield","Loras","Luther","Lycoming","Manchester","Marietta","Marymount",
      "MIT","Massachusetts-Boston","McDaniel","Messiah","Middlebury","Millikin",
      "Millsaps","Misericordia","Mount Union","Muhlenberg","Muskingum",
      "Nebraska Wesleyan","New England","New Jersey City","New York","Nichols",
      "North Central","North Park","Oberlin","Ohio Northern","Ohio Wesleyan",
      "Otterbein","Pacific Lutheran","Piedmont","Plattsburgh","Plymouth State",
      "Pomona-Pitzer","Randolph-Macon","Rhodes","Ripon","Rochester","Rowan",
      "Rutgers-Camden","Salve Regina","Skidmore","Smith","Southern Maine",
      "Springfield","St. John Fisher","St. Lawrence","St. Norbert","St. Olaf",
      "St. Thomas","Staten Island","Stevens","Stevenson","Stockton","Susquehanna",
      "Swarthmore","TCNJ","Texas Lutheran","Thomas More","Transylvania","Trinity",
      "Tufts","Union","Ursinus","Utica","Vassar","Wartburg","Washington",
      "Washington & Jefferson","Washington & Lee","Wesley","Western Connecticut",
      "Western New England","Westfield State","Westminster","Whittier","Whitworth",
      "Widener","Williams","Wittenberg","Worcester Polytechnic","York"
    ],
    "NAIA": [
      "Aquinas","Avila","Baker","Belhaven","Bethel","Biola","Briar Cliff","Bryan",
      "Carroll","Central Methodist","Coastal Georgia","College of Idaho","Columbia",
      "Concordia Ann Arbor","Concordia Seward","Corban","Cornerstone",
      "Culver-Stockton","Cumberland","Dakota State","Dakota Wesleyan","Davenport",
      "Doane","Dordt","Eastern Oregon","Embry-Riddle","Faulkner","Friends",
      "Georgetown College","Graceland","Grand View","Hannibal-LaGrange","Hastings",
      "Holy Names","Indiana Wesleyan","Iowa Wesleyan","John Brown","Judson",
      "Kansas Wesleyan","Keiser","Lewis-Clark State","Lindsey Wilson",
      "Lubbock Christian","Madonna","Malone","Mary Hardin-Baylor","Marian",
      "McPherson","MidAmerica Nazarene","Midland","Missouri Baptist",
      "Montana Western","Morningside","Mount Mercy","Mount Vernon Nazarene",
      "Northwestern Oklahoma","Northwestern","Ohio Christian","Oklahoma Baptist",
      "Oklahoma City","Oklahoma Wesleyan","Olivet Nazarene","Ottawa","Park",
      "Peru State","Point Loma Nazarene","Point Park","Reinhardt","Rio Grande",
      "Rocky Mountain","Saint Francis","Saint Xavier","Siena Heights","Simpson",
      "Southeastern","Southern Nazarene","Southern Oregon","Spring Arbor",
      "St. Ambrose","Sterling","Tabor","Taylor","Texas Wesleyan","Thomas",
      "Trinity International","Union","University of Jamestown","Vanguard",
      "Waldorf","Wayland Baptist","Webber International","William Carey",
      "William Jewell","William Penn"
    ],
    "NJCAA": [
      "Allegany","Allan Hancock","American River","Antelope Valley","Arizona Western",
      "Barton County","Blinn","Brookhaven","Butler County","Carl Albert State",
      "Central Arizona","Chabot","Cochise","Coffeyville","Colby","College of DuPage",
      "College of the Canyons","Connors State","Copiah-Lincoln","Cowley County",
      "Crowder","Diablo Valley","Dodge City","East Mississippi","Eastern Arizona",
      "El Camino","Fort Scott","Garden City","Glendale","Gulf Coast State",
      "Harford","Hinds","Holmes","Howard","Hutchinson","Indian Hills","Iowa Central",
      "Iowa Lakes","Iowa Western","Jacksonville","Jones County","Kansas City Kansas",
      "Kilgore","Labette County","Laney","Laramie County","Longview",
      "Los Angeles City","Los Angeles Harbor","Los Angeles Pierce","Los Angeles Valley",
      "McLennan","Mesa","Monroe","Mt. San Antonio","Nassau","Navarro",
      "Northeast Mississippi","Northeast Texas","Northwest Mississippi","Odessa",
      "Orange Coast","Palomar","Panola","Pasadena City","Pearl River",
      "Pensacola State","Phoenix","Pratt","Reedley","Riverside City",
      "Sacramento City","San Bernardino Valley","Santa Ana","Santa Barbara City",
      "Santa Monica","Santa Rosa Junior","Scottsdale","Seward County",
      "Shelton State","South Mountain","Southeastern Illinois","Southwest Tennessee",
      "Southwestern","Spokane Falls","State Fair Community","Tallahassee","Temple",
      "Trinity Valley","Tyler Junior","Vernon","Vincennes","Walters State",
      "Western Nebraska","Western Texas","Young Harris"
    ]
  },

  // ─── TENNIS ───────────────────────────────────────────────────────────────
  "Tennis - Men": {
    "NCAA D1": [
      "Air Force","Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor",
      "Boston College","Brown","California","Clemson","Columbia","Connecticut","Cornell",
      "Dartmouth","Denver","Duke","Florida","Florida State","Fresno State","Furman",
      "George Washington","Georgetown","Georgia","Georgia Tech","Harvard","Hawaii",
      "Illinois","Indiana","Iowa","Iowa State","Kansas","Kentucky","Louisville",
      "LSU","Maryland","Memphis","Miami","Michigan","Michigan State","Minnesota",
      "Mississippi State","Missouri","Nebraska","Nevada-Las Vegas","North Carolina",
      "North Carolina State","Northwestern","Notre Dame","Ohio State","Oklahoma",
      "Ole Miss","Oregon","Penn State","Pepperdine","Princeton","Purdue","Rice",
      "Rutgers","San Diego","San Diego State","South Carolina","South Florida",
      "Stanford","Syracuse","TCU","Tennessee","Texas","Texas A&M","Texas Tech",
      "Tulane","Tulsa","UCLA","USC","Utah","Vanderbilt","Virginia","Virginia Tech",
      "Wake Forest","Washington","West Virginia","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "Armstrong","Barry","Cal Poly Pomona","Cal State LA","California Baptist",
      "Columbus State","Eckerd","Emporia State","Ferris State","Florida Southern",
      "Florida Tech","Francis Marion","Grand Canyon","Holy Names","Indianapolis",
      "Lander","Le Moyne","Lindenwood","Lynn","Midwestern State","Minnesota Duluth",
      "Missouri Southern","Nebraska-Kearney","New Haven","Newman","North Alabama",
      "North Florida","Northern Michigan","Nova Southeastern","Quincy","Rollins",
      "St. Leo","Tarleton State","Texas A&M Commerce","Tiffin","Truman State",
      "UC San Diego","Upper Iowa","West Alabama","West Florida","West Georgia",
      "Western New Mexico","Young Harris"
    ],
    "NCAA D3": [
      "Amherst","Babson","Bates","Bowdoin","Brandeis","Cal Lutheran","Carleton",
      "Carnegie Mellon","Case Western Reserve","Christopher Newport","Claremont McKenna",
      "Colby","Connecticut College","DePauw","Dickinson","Emory","Gettysburg",
      "Hamilton","Haverford","Illinois Wesleyan","Ithaca","Johns Hopkins","Kalamazoo",
      "Kenyon","Lake Forest","Lawrence","Middlebury","MIT","Muhlenberg",
      "North Central","Oberlin","Pomona-Pitzer","Principia","Redlands","Rhodes",
      "Rochester","Rose-Hulman","St. Lawrence","St. Olaf","St. Thomas","Swarthmore",
      "Trinity","Tufts","UC Santa Cruz","Union","Ursinus","Washington",
      "Washington & Lee","Wesleyan","Whitman","Whitworth","Williams","Wittenberg"
    ],
    "NAIA": [
      "Aquinas","Bethel","Biola","Bryan","College of Idaho","Concordia Ann Arbor",
      "Cornerstone","Culver-Stockton","Cumberland","Davenport","Doane","Embry-Riddle",
      "Faulkner","Friends","Georgetown College","Grand View","Hastings",
      "Holy Names","Indiana Wesleyan","John Brown","Keiser","Lewis-Clark State",
      "Lindsey Wilson","Lubbock Christian","Madonna","Malone","Mary Hardin-Baylor",
      "MidAmerica Nazarene","Midland","Missouri Baptist","Morningside",
      "Mount Vernon Nazarene","Northwestern","Ohio Christian","Oklahoma Baptist",
      "Oklahoma City","Olivet Nazarene","Point Loma Nazarene","Reinhardt",
      "Rocky Mountain","Saint Francis","Saint Xavier","Siena Heights","Simpson",
      "Southeastern","Southern Nazarene","Spring Arbor","St. Ambrose",
      "Taylor","Texas Wesleyan","Union","Vanguard","Wayland Baptist",
      "Webber International","William Carey","William Jewell"
    ]
  },

  "Tennis - Women": {
    "NCAA D1": [
      "Air Force","Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor",
      "Boston College","Brown","California","Clemson","Columbia","Connecticut",
      "Dartmouth","Denver","Duke","Florida","Florida State","Fresno State","Furman",
      "George Washington","Georgetown","Georgia","Georgia Tech","Harvard","Hawaii",
      "Illinois","Indiana","Iowa","Iowa State","Kansas","Kentucky","Louisville",
      "LSU","Maryland","Memphis","Miami","Michigan","Michigan State","Minnesota",
      "Mississippi State","Missouri","Nebraska","Nevada-Las Vegas","North Carolina",
      "North Carolina State","Northwestern","Notre Dame","Ohio State","Oklahoma",
      "Ole Miss","Oregon","Penn State","Pepperdine","Princeton","Purdue","Rice",
      "Rutgers","San Diego","San Diego State","South Carolina","South Florida",
      "Stanford","Syracuse","TCU","Tennessee","Texas","Texas A&M","Texas Tech",
      "Tulane","UCLA","USC","Utah","Vanderbilt","Virginia","Virginia Tech",
      "Wake Forest","Washington","West Virginia","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "Armstrong","Barry","Cal Poly Pomona","Cal State LA","California Baptist",
      "Columbus State","Eckerd","Emporia State","Florida Southern","Florida Tech",
      "Francis Marion","Grand Canyon","Indianapolis","Le Moyne","Lindenwood","Lynn",
      "Midwestern State","Minnesota Duluth","Nebraska-Kearney","New Haven",
      "North Alabama","North Florida","Nova Southeastern","Quincy","Rollins",
      "St. Leo","Texas A&M Commerce","Tiffin","West Alabama","West Florida",
      "West Georgia","Young Harris"
    ],
    "NCAA D3": [
      "Amherst","Babson","Bates","Bowdoin","Brandeis","Cal Lutheran","Carleton",
      "Carnegie Mellon","Case Western Reserve","Christopher Newport","Claremont McKenna",
      "Colby","Connecticut College","DePauw","Dickinson","Emory","Gettysburg",
      "Hamilton","Haverford","Illinois Wesleyan","Ithaca","Johns Hopkins","Kalamazoo",
      "Kenyon","Lake Forest","Lawrence","Middlebury","MIT","Muhlenberg",
      "North Central","Oberlin","Pomona-Pitzer","Rhodes","Rochester","St. Lawrence",
      "St. Olaf","St. Thomas","Swarthmore","Trinity","Tufts","Union","Ursinus",
      "Washington","Washington & Lee","Wesleyan","Whitman","Williams","Wittenberg"
    ],
    "NAIA": [
      "Aquinas","Bethel","Biola","Bryan","College of Idaho","Concordia Ann Arbor",
      "Cornerstone","Cumberland","Davenport","Doane","Embry-Riddle","Faulkner",
      "Friends","Georgetown College","Grand View","Hastings","Holy Names",
      "Indiana Wesleyan","John Brown","Keiser","Lewis-Clark State","Lindsey Wilson",
      "Lubbock Christian","Madonna","Malone","Mary Hardin-Baylor","MidAmerica Nazarene",
      "Midland","Missouri Baptist","Morningside","Mount Vernon Nazarene",
      "Northwestern","Ohio Christian","Oklahoma Baptist","Oklahoma City",
      "Olivet Nazarene","Point Loma Nazarene","Reinhardt","Rocky Mountain",
      "Saint Francis","Saint Xavier","Siena Heights","Southeastern",
      "Southern Nazarene","Spring Arbor","St. Ambrose","Taylor","Texas Wesleyan",
      "Union","Vanguard","Wayland Baptist","Webber International","William Carey"
    ]
  },

  // ─── GOLF ─────────────────────────────────────────────────────────────────
  "Golf - Men": {
    "NCAA D1": [
      "Air Force","Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor",
      "Boston College","BYU","California","Campbell","Clemson","Coastal Carolina",
      "Colorado","Colorado State","Connecticut","Davidson","Duke","East Tennessee State",
      "Elon","Furman","Georgia","Georgia Southern","Georgia Tech","Gonzaga","Harvard",
      "Houston","Illinois","Indiana","Iowa","Iowa State","Jacksonville",
      "Kansas","Kansas State","Kennesaw State","Kentucky","Lamar","Liberty",
      "Louisville","LSU","Maryland","Memphis","Miami","Michigan","Michigan State",
      "Mississippi State","Missouri","Nebraska","New Mexico","New Mexico State",
      "North Carolina","North Carolina State","Northwestern","Notre Dame","Ohio State",
      "Oklahoma","Oklahoma State","Ole Miss","Oral Roberts","Oregon","Oregon State",
      "Penn State","Pepperdine","Purdue","Rice","Richmond","Rutgers",
      "Sam Houston State","Samford","San Diego","San Diego State","San Francisco",
      "South Carolina","South Florida","Stanford","TCU","Tennessee","Texas",
      "Texas A&M","Texas State","Texas Tech","Tulane","Tulsa","UCLA","USC",
      "Utah","Vanderbilt","Virginia","Virginia Tech","Wake Forest","Washington",
      "Washington State","West Virginia","Western Kentucky","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "Armstrong","Barry","Cal Poly Pomona","California Baptist","Carson-Newman",
      "Central Missouri","Chico State","Colorado Mesa","Columbus State",
      "Concordia Irvine","Delta State","Drury","East Central","Emporia State",
      "Ferris State","Findlay","Florida Southern","Florida Tech","Fort Hays State",
      "Francis Marion","Gannon","Grand Canyon","Grand Valley State","Henderson State",
      "Indianapolis","Johnson C. Smith","Le Moyne","Lindenwood","Lynn",
      "Midwestern State","Minnesota Duluth","Minnesota State Mankato","Missouri Western",
      "Nebraska-Kearney","New Haven","Newman","North Alabama","North Georgia",
      "Northern Michigan","Northwest Missouri State","Northwood","Nova Southeastern",
      "Ohio Dominican","Oklahoma Christian","Ouachita Baptist","Palm Beach Atlantic",
      "Pittsburg State","Queens","Quincy","Regis","Rockhurst","Rogers State",
      "Rollins","St. Cloud State","St. Leo","Tarleton State","Texas A&M Commerce",
      "Tiffin","Truman State","Tusculum","UC San Diego","Upper Iowa",
      "Wayne State","West Florida","West Georgia","West Texas A&M","Western New Mexico"
    ],
    "NCAA D3": [
      "Allegheny","Amherst","Aurora","Babson","Bates","Berry","Bowdoin",
      "Cal Lutheran","Carleton","Carnegie Mellon","Carthage","Case Western Reserve",
      "Christopher Newport","Claremont McKenna","Coe","Colby","Colorado College",
      "Connecticut College","DePauw","Dickinson","Emory","Gettysburg","Grove City",
      "Gustavus Adolphus","Hamilton","Hanover","Hardin-Simmons","Heidelberg",
      "Hope","Huntingdon","Illinois Wesleyan","Ithaca","John Carroll","Kalamazoo",
      "Kenyon","Knox","Lake Forest","Lawrence","Loras","Luther","Manchester",
      "Marietta","Middlebury","Millikin","Millsaps","Mount Union","Muhlenberg",
      "Muskingum","Nebraska Wesleyan","North Central","North Park","Ohio Northern",
      "Ohio Wesleyan","Otterbein","Piedmont","Randolph-Macon","Rhodes","Ripon",
      "Rochester","Rose-Hulman","St. John Fisher","St. Lawrence","St. Norbert",
      "St. Olaf","St. Thomas","Stevens","Thomas More","Transylvania","Trinity",
      "Tufts","Union","Ursinus","Wabash","Wartburg","Washington","Washington & Jefferson",
      "Washington & Lee","Wesleyan","Whitworth","Williams","Wittenberg"
    ],
    "NAIA": [
      "Baker","Belhaven","Bethel","Biola","Bryan","Carroll","Central Methodist",
      "College of Idaho","Columbia","Concordia Ann Arbor","Cornerstone",
      "Culver-Stockton","Cumberland","Davenport","Doane","Dordt","Embry-Riddle",
      "Faulkner","Friends","Georgetown College","Graceland","Grand View",
      "Hastings","Indiana Wesleyan","John Brown","Kansas Wesleyan","Keiser",
      "Lewis-Clark State","Lindsey Wilson","Lubbock Christian","Madonna","Malone",
      "Mary Hardin-Baylor","MidAmerica Nazarene","Midland","Missouri Baptist",
      "Morningside","Mount Vernon Nazarene","Northwestern Oklahoma","Ohio Christian",
      "Oklahoma Baptist","Oklahoma City","Oklahoma Wesleyan","Olivet Nazarene",
      "Ottawa","Park","Point Loma Nazarene","Reinhardt","Rio Grande",
      "Rocky Mountain","Saint Francis","Science & Arts Oklahoma","Siena Heights",
      "Southeastern","Southern Nazarene","St. Ambrose","Sterling","Tabor",
      "Taylor","Texas Wesleyan","Union","Vanguard","Wayland Baptist",
      "Webber International","William Carey","William Jewell","William Penn"
    ]
  },

  "Golf - Women": {
    "NCAA D1": [
      "Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor","California",
      "Clemson","Colorado","Colorado State","Duke","Florida","Florida State",
      "Furman","Georgia","Georgia Tech","Harvard","Houston","Illinois","Indiana",
      "Iowa","Iowa State","Kansas","Kansas State","Kentucky","LSU","Maryland",
      "Memphis","Miami","Michigan","Michigan State","Minnesota","Mississippi State",
      "Missouri","Nebraska","New Mexico","North Carolina","North Carolina State",
      "Northwestern","Notre Dame","Ohio State","Oklahoma","Oklahoma State","Ole Miss",
      "Oregon","Penn State","Pepperdine","Purdue","Rice","Rutgers","San Diego State",
      "South Carolina","South Florida","Stanford","Syracuse","TCU","Tennessee",
      "Texas","Texas A&M","Texas Tech","Tulane","UCLA","USC","Utah","Vanderbilt",
      "Virginia","Virginia Tech","Wake Forest","Washington","West Virginia","Wisconsin"
    ],
    "NCAA D2": [
      "Armstrong","Barry","California Baptist","Carson-Newman","Central Missouri",
      "Colorado Mesa","Columbus State","Delta State","Drury","Emporia State",
      "Ferris State","Florida Southern","Florida Tech","Francis Marion","Gannon",
      "Grand Canyon","Grand Valley State","Henderson State","Indianapolis","Le Moyne",
      "Lindenwood","Lynn","Minnesota Duluth","Nebraska-Kearney","New Haven",
      "North Alabama","North Georgia","Northwood","Nova Southeastern",
      "Oklahoma Christian","Palm Beach Atlantic","Queens","Quincy","Rollins",
      "St. Leo","Tarleton State","Texas A&M Commerce","Truman State","UC San Diego",
      "West Florida","West Georgia","West Texas A&M"
    ],
    "NCAA D3": [
      "Allegheny","Amherst","Aurora","Babson","Berry","Bowdoin","Cal Lutheran",
      "Carleton","Carnegie Mellon","Case Western Reserve","Christopher Newport",
      "Claremont McKenna","Colby","Colorado College","DePauw","Dickinson","Emory",
      "Gettysburg","Gustavus Adolphus","Hamilton","Hope","Illinois Wesleyan","Ithaca",
      "Johns Hopkins","Kalamazoo","Kenyon","Lake Forest","Lawrence","Loras",
      "Luther","Manchester","Middlebury","Millikin","Mount Union","Muhlenberg",
      "Nebraska Wesleyan","North Central","Ohio Wesleyan","Otterbein","Piedmont",
      "Randolph-Macon","Rhodes","Rochester","St. Lawrence","St. Olaf","St. Thomas",
      "Thomas More","Trinity","Tufts","Union","Ursinus","Wartburg","Washington",
      "Washington & Lee","Wesleyan","Whitworth","Williams","Wittenberg"
    ],
    "NAIA": [
      "Baker","Belhaven","Bethel","Biola","Bryan","Carroll","Central Methodist",
      "College of Idaho","Concordia Ann Arbor","Cornerstone","Cumberland","Davenport",
      "Doane","Embry-Riddle","Faulkner","Friends","Georgetown College","Grand View",
      "Hastings","Holy Names","Indiana Wesleyan","John Brown","Keiser",
      "Lewis-Clark State","Lindsey Wilson","Lubbock Christian","Madonna","Malone",
      "Mary Hardin-Baylor","MidAmerica Nazarene","Midland","Missouri Baptist",
      "Morningside","Mount Vernon Nazarene","Northwestern","Ohio Christian",
      "Oklahoma Baptist","Oklahoma City","Olivet Nazarene","Ottawa","Park",
      "Point Loma Nazarene","Reinhardt","Rocky Mountain","Saint Francis","Saint Xavier",
      "Siena Heights","Southeastern","Southern Nazarene","Spring Arbor","St. Ambrose",
      "Sterling","Tabor","Taylor","Texas Wesleyan","Union","Vanguard",
      "Wayland Baptist","Webber International","William Carey","William Jewell"
    ]
  },

  // ─── VOLLEYBALL ───────────────────────────────────────────────────────────
  "Volleyball - Women": {
    "NCAA D1": [
      "Air Force","Akron","Alabama","Albany","Arizona","Arizona State","Arkansas",
      "Arkansas State","Army","Auburn","Austin Peay","Ball State","Baylor",
      "Belmont","Boston College","Bowling Green","BYU","Cal Poly","California",
      "Campbell","Central Arkansas","Central Michigan","Charlotte","Cincinnati",
      "Clemson","Coastal Carolina","Colorado","Colorado State","Connecticut",
      "Creighton","Davidson","Dayton","Delaware","Denver","Duke","East Carolina",
      "Elon","Fairfield","Florida","Florida Atlantic","Florida Gulf Coast",
      "Florida International","Florida State","Fordham","Fresno State","Furman",
      "George Mason","Georgia","Georgia Southern","Georgia State","Georgia Tech",
      "Gonzaga","Grand Canyon","Hawaii","High Point","Hofstra","Houston",
      "Illinois","Illinois State","Indiana","Iowa","Iowa State","IUPUI",
      "Jacksonville State","James Madison","Kansas","Kansas State","Kennesaw State",
      "Kent State","Kentucky","La Salle","Lafayette","Lehigh","Liberty","Longwood",
      "Louisiana","Louisville","Loyola Chicago","Loyola Marymount","LSU","Maine",
      "Manhattan","Marist","Marquette","Marshall","Maryland","Massachusetts",
      "Memphis","Mercer","Miami","Miami (OH)","Michigan","Michigan State",
      "Middle Tennessee","Minnesota","Mississippi State","Missouri","Monmouth",
      "Montana","Montana State","Morehead State","Murray State","Nebraska",
      "Nevada","Nevada-Las Vegas","New Hampshire","New Mexico","New Mexico State",
      "North Carolina","North Carolina State","North Dakota","North Dakota State",
      "Northeastern","Northern Arizona","Northern Colorado","Northern Iowa",
      "Northwestern","Notre Dame","Ohio","Ohio State","Oklahoma","Ole Miss",
      "Old Dominion","Oral Roberts","Oregon","Oregon State","Penn State",
      "Pepperdine","Pittsburgh","Portland","Portland State","Princeton","Purdue",
      "Rice","Rutgers","Sacramento State","Saint Louis","Sam Houston State",
      "Samford","San Diego","San Diego State","San Francisco","Santa Barbara",
      "Seattle U","Seton Hall","SMU","South Carolina","South Florida",
      "South Dakota","South Dakota State","Southeastern Louisiana","Southern Illinois",
      "Stanford","Stetson","Syracuse","TCU","Temple","Tennessee","Tennessee Tech",
      "Texas","Texas A&M","Texas State","Texas Tech","Toledo","Troy","Tulsa",
      "UC Davis","UC Irvine","UC Riverside","UCLA","UCF","UNLV","USC","Utah",
      "Utah State","Utah Valley","Vanderbilt","Vermont","Villanova","Virginia",
      "Virginia Commonwealth","Virginia Tech","Wake Forest","Washington",
      "Washington State","Weber State","West Virginia","Western Illinois",
      "Western Kentucky","Wisconsin","Wofford","Wyoming","Xavier"
    ],
    "NCAA D2": [
      "Adelphi","Alabama in Huntsville","Angelo State","Augustana","Barry",
      "Bentley","Bloomsburg","California Baptist","Cal State LA","Cal State Bakersfield",
      "Cal State Northridge","Cal State San Bernardino","Carson-Newman",
      "Central Missouri","Charleston","Chico State","Colorado Mesa","Colorado Mines",
      "Colorado State-Pueblo","Columbus State","Concordia Irvine","Concordia St. Paul",
      "Delta State","Dominican","Drury","East Stroudsburg","Eastern New Mexico",
      "Emporia State","Ferris State","Findlay","Florida Southern","Florida Tech",
      "Fort Hays State","Francis Marion","Gannon","Georgia College","Grand Canyon",
      "Grand Valley State","Hawaii Pacific","Henderson State","Holy Family",
      "Indianapolis","Indiana PA","Kutztown","Le Moyne","Lenoir-Rhyne","Lewis",
      "Lincoln Memorial","Lynn","Mars Hill","Mercyhurst","Michigan Tech",
      "Midwestern State","Minnesota Duluth","Minnesota State Mankato",
      "Missouri Southern","Missouri Western","Molloy","Mount Olive",
      "Nebraska-Kearney","New Haven","Newman","North Alabama","North Greenville",
      "Northeastern State","Northern Michigan","Northern State",
      "Northwest Missouri State","Northwood","Nova Southeastern","Ohio Dominican",
      "Oklahoma Christian","Palm Beach Atlantic","Pfeiffer","Pittsburg State",
      "Queens","Quincy","Regis","Roberts Wesleyan","Rockhurst","Rollins",
      "Sacramento State","San Francisco State","Seattle Pacific","Shepherd",
      "Shippensburg","Sioux Falls","Slippery Rock","South Carolina Aiken",
      "Southern Arkansas","Southern Connecticut","Southwest Baptist",
      "Southwest Minnesota State","St. Cloud State","St. Leo","St. Martin's",
      "Tarleton State","Texas A&M Commerce","Tiffin","Truman State","Tusculum",
      "UC San Diego","Upper Iowa","Virginia State","Wayne State","West Alabama",
      "West Chester","West Florida","West Georgia","West Liberty",
      "West Texas A&M","Western Oregon","Wingate","Winona State"
    ],
    "NCAA D3": [
      "Adrian","Albion","Albright","Alfred","Allegheny","Alma","Amherst",
      "Anderson","Anna Maria","Arcadia","Augustana","Aurora","Babson",
      "Baldwin Wallace","Bates","Beloit","Benedictine","Berry","Bethel",
      "Bowdoin","Brandeis","Bridgewater","Brockport","Buena Vista","Buffalo State",
      "Cabrini","Cal Lutheran","Calvin","Capital","Carleton","Carnegie Mellon",
      "Carroll","Carthage","Case Western Reserve","Catholic","Chapman",
      "Christopher Newport","Clark","Coe","Colby","Colorado College",
      "Connecticut College","Cortland","Curry","Delaware Valley","DePauw",
      "Dickinson","Elmhurst","Elmira","Emory","Endicott","Fitchburg State",
      "Franklin","Franklin & Marshall","Fredonia","Frostburg State","Gettysburg",
      "Gordon","Goucher","Greensboro","Grove City","Guilford","Gustavus Adolphus",
      "Hamilton","Hamline","Hanover","Hardin-Simmons","Haverford","Heidelberg",
      "Hiram","Hope","Huntingdon","Illinois Wesleyan","Ithaca","John Carroll",
      "Johns Hopkins","Kalamazoo","Keene State","Kenyon","Knox","La Roche",
      "Lake Forest","Lakeland","Lawrence","Lebanon Valley","Lewis & Clark",
      "Linfield","Loras","Luther","Lycoming","Manchester","Marietta","Marymount",
      "MIT","Massachusetts-Boston","McDaniel","Messiah","Middlebury","Millikin",
      "Millsaps","Misericordia","Mount Union","Muhlenberg","Muskingum",
      "Nebraska Wesleyan","New England","New Jersey City","New York","Nichols",
      "North Central","North Park","Oberlin","Ohio Northern","Ohio Wesleyan",
      "Otterbein","Pacific Lutheran","Piedmont","Plattsburgh","Plymouth State",
      "Pomona-Pitzer","Randolph-Macon","Rhodes","Ripon","Rochester","Rowan",
      "Rutgers-Camden","Salve Regina","Skidmore","Smith","Southern Maine",
      "Springfield","St. John Fisher","St. Lawrence","St. Norbert","St. Olaf",
      "St. Thomas","Staten Island","Stevens","Stevenson","Stockton","Susquehanna",
      "Swarthmore","TCNJ","Texas Lutheran","Thomas More","Transylvania","Trinity",
      "Tufts","Union","Ursinus","Utica","Vassar","Wartburg","Washington",
      "Washington & Jefferson","Washington & Lee","Wesley","Western Connecticut",
      "Western New England","Westfield State","Westminster","Whittier","Whitworth",
      "Widener","Williams","Wittenberg","Worcester Polytechnic","York"
    ],
    "NAIA": [
      "Aquinas","Avila","Baker","Belhaven","Benedictine","Bethel","Biola",
      "Briar Cliff","Bryan","Calumet St. Joseph","Carroll","Central Christian",
      "Central Methodist","Chadron State","Cleary","Coastal Georgia","College of Idaho",
      "Columbia","Concordia Ann Arbor","Concordia Seward","Corban","Cornerstone",
      "Culver-Stockton","Cumberland","Dakota State","Dakota Wesleyan","Davenport",
      "Doane","Dordt","Eastern Oregon","Embry-Riddle","Faulkner","Friends",
      "Georgetown College","Graceland","Grand View","Hannibal-LaGrange","Hastings",
      "Holy Names","Indiana Wesleyan","Iowa Wesleyan","John Brown","Judson",
      "Kansas Wesleyan","Keiser","Lawrence Tech","Lewis-Clark State","Lindsey Wilson",
      "Lubbock Christian","Madonna","Malone","Mary Hardin-Baylor","Marian",
      "McPherson","MidAmerica Nazarene","Midland","Midway","Missouri Baptist",
      "Montana Western","Morningside","Mount Mercy","Mount Vernon Nazarene",
      "Northwestern Oklahoma","Northwestern","Ohio Christian","Oklahoma Baptist",
      "Oklahoma City","Oklahoma Wesleyan","Olivet Nazarene","Ottawa","Park",
      "Peru State","Point Loma Nazarene","Point Park","Reinhardt","Rio Grande",
      "Rocky Mountain","Saint Francis","Saint Xavier","Science & Arts Oklahoma",
      "Siena Heights","Simpson","Southeastern","Southern Nazarene","Southern Oregon",
      "Spring Arbor","St. Ambrose","St. Thomas","Sterling","Tabor","Taylor",
      "Texas College","Texas Wesleyan","Thomas","Trinity International","Union",
      "University of Jamestown","Vanguard","Waldorf","Wayland Baptist",
      "Webber International","William Carey","William Jewell","William Penn"
    ]
  },

  // ─── BASEBALL ─────────────────────────────────────────────────────────────
  "Baseball - Men": {
    "NCAA D1": [
      "Air Force","Akron","Alabama","Albany","Arizona","Arizona State","Arkansas",
      "Arkansas State","Army","Auburn","Austin Peay","Ball State","Baylor",
      "Belmont","Boston College","Bradley","Bryant","Bucknell","Campbell",
      "Central Arkansas","Central Michigan","Charlotte","Cincinnati","Clemson",
      "Coastal Carolina","Colorado","Columbia","Connecticut","Creighton",
      "Dallas Baptist","Davidson","Delaware","East Carolina","East Tennessee State",
      "Eastern Illinois","Eastern Kentucky","Elon","Fairfield","Florida",
      "Florida Atlantic","Florida Gulf Coast","Florida International","Florida State",
      "Fordham","Fresno State","Furman","Gardner-Webb","George Mason",
      "Georgia","Georgia Southern","Georgia State","Georgia Tech","Gonzaga",
      "Grand Canyon","Harvard","High Point","Houston","Illinois",
      "Illinois State","Indiana","Iowa","Iowa State","Jacksonville",
      "Jacksonville State","James Madison","Kansas","Kansas State",
      "Kennesaw State","Kent State","Kentucky","La Salle","Lafayette",
      "Lamar","Le Moyne","Liberty","Long Island","Longwood","Louisiana",
      "Louisiana Monroe","Louisiana Tech","Louisville","Loyola Marymount",
      "LSU","Maine","Manhattan","Marist","Marshall","Maryland","Massachusetts",
      "Memphis","Mercer","Miami","Miami (OH)","Michigan","Michigan State",
      "Middle Tennessee","Minnesota","Mississippi State","Missouri",
      "Missouri State","Nebraska","Nevada","New Mexico","New Orleans",
      "North Carolina","North Carolina State","North Dakota State","North Florida",
      "Northeastern","Northern Illinois","Northwestern","Notre Dame","Ohio",
      "Ohio State","Oklahoma","Oklahoma State","Ole Miss","Old Dominion",
      "Oral Roberts","Oregon","Oregon State","Penn State","Pepperdine",
      "Pittsburgh","Princeton","Purdue","Rice","Richmond","Rider",
      "Robert Morris","Rutgers","Sacramento State","Saint John's","Saint Louis",
      "Sam Houston State","Samford","San Diego","San Diego State","San Jose State",
      "Santa Barbara","Seton Hall","South Carolina","South Florida",
      "Southeast Missouri State","Southeastern Louisiana","Southern Illinois",
      "Stanford","Stetson","TCU","Temple","Tennessee","Texas","Texas A&M",
      "Texas State","Texas Tech","Toledo","Troy","Tulane","Tulsa","UC Davis",
      "UC Irvine","UC Riverside","UCLA","UCF","UNLV","USC","Utah","Utah Valley",
      "Valparaiso","Vanderbilt","Vermont","Virginia","Virginia Commonwealth",
      "Virginia Tech","Wake Forest","Washington","Washington State","West Virginia",
      "Western Carolina","Western Kentucky","Wichita State","William & Mary",
      "Winthrop","Wisconsin-Milwaukee","Wright State","Xavier","Yale"
    ],
    "NCAA D2": [
      "Adelphi","Alabama in Huntsville","Angelo State","Assumption","Augustana",
      "Barry","Bellarmine","Bentley","Bloomsburg","Bowie State",
      "California Baptist","Cal State LA","Cal State San Bernardino","Cameron",
      "Carson-Newman","Central Missouri","Charleston","Chico State",
      "Colorado Mesa","Colorado State-Pueblo","Columbus State","Concordia Irvine",
      "Delta State","Drury","East Central","East Stroudsburg","Eastern New Mexico",
      "Edinboro","Emporia State","Ferris State","Findlay","Florida Southern",
      "Florida Tech","Fort Hays State","Fort Lewis","Francis Marion","Gannon",
      "Georgia College","Grand Canyon","Grand Valley State","Henderson State",
      "Hillsdale","Indianapolis","Indiana PA","Johnson C. Smith","Le Moyne",
      "Lenoir-Rhyne","Lewis","Lincoln Memorial","Lock Haven","Lynn",
      "Mars Hill","Mercyhurst","Michigan Tech","Midwestern State","Minnesota Duluth",
      "Minnesota State Mankato","Missouri Southern","Missouri Western","Mount Olive",
      "Nebraska-Kearney","New Haven","Newman","North Alabama","North Greenville",
      "Northern Michigan","Northwest Missouri State","Northwood",
      "Notre Dame de Namur","Nova Southeastern","Ohio Dominican",
      "Oklahoma Christian","Ouachita Baptist","Palm Beach Atlantic","Pfeiffer",
      "Philadelphia","Pittsburg State","Queens","Quincy","Regis","Roberts Wesleyan",
      "Rockhurst","Rogers State","Rollins","Saginaw Valley State","Salem International",
      "San Francisco State","Seattle Pacific","Shepherd","Shippensburg",
      "Slippery Rock","South Carolina Aiken","Southern Arkansas","Southern Connecticut",
      "Southwest Baptist","St. Cloud State","St. Leo","Tarleton State",
      "Texas A&M Commerce","Texas A&M International","Tiffin","Truman State",
      "Tusculum","Upper Iowa","Wayne State","West Alabama","West Chester",
      "West Florida","West Georgia","West Liberty","West Texas A&M",
      "Western New Mexico","Western Oregon","Wingate","Winona State"
    ],
    "NAIA": [
      "Aquinas","Avila","Baker","Belhaven","Bethel","Biola","Briar Cliff","Bryan",
      "Carroll","Central Methodist","Chadron State","Coastal Georgia","College of Idaho",
      "Columbia","Concordia Ann Arbor","Concordia Seward","Corban","Cornerstone",
      "Culver-Stockton","Cumberland","Dakota State","Dakota Wesleyan","Davenport",
      "Doane","Dordt","Eastern Oregon","Edward Waters","Embry-Riddle","Faulkner",
      "Friends","Georgetown College","Graceland","Grand View","Hannibal-LaGrange",
      "Hastings","Indiana Wesleyan","Iowa Wesleyan","Jarvis Christian","John Brown",
      "Judson","Kansas Wesleyan","Keiser","Langston","Lewis-Clark State",
      "Lindsey Wilson","Lubbock Christian","Madonna","Malone","Mary Hardin-Baylor",
      "Marian","McPherson","MidAmerica Nazarene","Midland","Midway","Missouri Baptist",
      "Montana Western","Morningside","Mount Mercy","Mount Vernon Nazarene",
      "Northwestern Oklahoma","Northwestern","Ohio Christian","Oklahoma Baptist",
      "Oklahoma City","Oklahoma Wesleyan","Olivet Nazarene","Ottawa","Park",
      "Peru State","Point Loma Nazarene","Point Park","Reinhardt","Rio Grande",
      "Rocky Mountain","Saint Francis","Saint Xavier","Science & Arts Oklahoma",
      "Siena Heights","Simpson","Southeastern","Southern Nazarene","Southern Oregon",
      "Spring Arbor","St. Ambrose","Sterling","Tabor","Taylor","Texas College",
      "Texas Wesleyan","Thomas","Trinity International","Union",
      "University of Jamestown","Vanguard","Waldorf","Wayland Baptist",
      "Webber International","William Carey","William Jewell","William Penn"
    ],
    "NJCAA": [
      "Allegany","Barton County","Blinn","Brookhaven","Butler County",
      "Carl Albert State","Central Arizona","Chabot","Cisco","Cochise","Coffeyville",
      "Colby","Connors State","Copiah-Lincoln","Cowley County","Crowder",
      "Darton State","Dodge City","East Mississippi","Eastern Arizona",
      "Eastern Oklahoma","El Camino","Enterprise State","Fort Scott","Garden City",
      "Gulf Coast State","Harford","Hinds","Holmes","Howard","Hutchinson",
      "Indian Hills","Iowa Central","Iowa Western","Jacksonville","Jones County",
      "Kansas City Kansas","Kilgore","Labette County","Laramie County","Longview",
      "Los Angeles Harbor","LSU Eunice","McLennan","Mesa","Miles",
      "Mississippi Delta","Mississippi Gulf Coast","Monroe","Mt. San Antonio",
      "Nassau","Navarro","Northeast Mississippi","Northeast Texas",
      "Northwest Mississippi","Odessa","Panola","Pasadena City","Pearl River",
      "Pensacola State","Phoenix","Pratt","Ranger","Reedley","Riverside City",
      "Sacramento City","San Bernardino Valley","Scottsdale","Seward County",
      "Shelton State","Snead State","Southeast","State Fair Community",
      "Sullivan County","Tallahassee","Temple","Trinity Valley","Tyler Junior",
      "Vernon","Vincennes","Walters State","Western Nebraska","Western Texas",
      "Young Harris"
    ]
  },

  // ─── BASKETBALL ───────────────────────────────────────────────────────────
  "Basketball - Men": {
    "NCAA D1": [
      "Abilene Christian","Air Force","Akron","Alabama","Alabama A&M","Alabama State",
      "Albany","Alcorn State","American","Appalachian State","Arizona","Arizona State",
      "Arkansas","Arkansas-Pine Bluff","Army","Auburn","Austin Peay","Ball State",
      "Baylor","Bellarmine","Belmont","Bethune-Cookman","Boise State","Boston College",
      "Boston University","Bowling Green","Bradley","Brown","Bryant","Bucknell",
      "Buffalo","Butler","Cal Poly","California","Campbell","Canisius",
      "Central Arkansas","Central Connecticut State","Charlotte","Chattanooga",
      "Chicago State","Cincinnati","Clemson","Cleveland State","Coastal Carolina",
      "Colgate","Colorado","Colorado State","Columbia","Connecticut","Coppin State",
      "Cornell","Creighton","Davidson","Dayton","Delaware","Delaware State",
      "DePaul","Detroit Mercy","Drake","Drexel","Duke","Duquesne","East Carolina",
      "East Tennessee State","Eastern Illinois","Eastern Kentucky","Elon","Evansville",
      "Fairfield","Florida","Florida A&M","Florida Atlantic","Florida Gulf Coast",
      "Florida International","Florida State","Fordham","Fresno State","Furman",
      "George Mason","George Washington","Georgetown","Georgia","Georgia Southern",
      "Georgia State","Georgia Tech","Gonzaga","Grambling State","Grand Canyon",
      "Hampton","Hartford","Harvard","Hawaii","High Point","Hofstra","Holy Cross",
      "Houston","Howard","Idaho","Idaho State","Illinois","Illinois-Chicago",
      "Illinois State","Indiana","Indiana State","Iona","Iowa","Iowa State",
      "Jacksonville","Jacksonville State","James Madison","Kansas","Kansas State",
      "Kennesaw State","Kent State","Kentucky","La Salle","Lafayette","Lamar",
      "Lehigh","Liberty","Lipscomb","Little Rock","Long Island","Longwood",
      "Louisiana","Louisiana Monroe","Louisiana Tech","Louisville","Loyola Chicago",
      "Loyola Maryland","Loyola Marymount","LSU","Maine","Manhattan","Marist",
      "Marquette","Marshall","Maryland","McNeese State","Memphis","Mercer",
      "Miami","Miami (OH)","Michigan","Michigan State","Middle Tennessee","Milwaukee",
      "Minnesota","Mississippi State","Mississippi Valley State","Missouri",
      "Missouri State","Monmouth","Montana","Montana State","Morehead State",
      "Morgan State","Murray State","Navy","Nebraska","Nevada","Nevada-Las Vegas",
      "New Hampshire","New Mexico","New Mexico State","Niagara","Nicholls State",
      "Norfolk State","North Carolina","North Carolina A&T","North Carolina Central",
      "North Carolina State","North Dakota","North Dakota State","North Florida",
      "Northeastern","Northern Arizona","Northern Colorado","Northern Illinois",
      "Northern Iowa","Northern Kentucky","Northwestern","Northwestern State",
      "Notre Dame","Oakland","Ohio","Ohio State","Oklahoma","Oklahoma State",
      "Ole Miss","Oral Roberts","Oregon","Oregon State","Penn State","Pennsylvania",
      "Pepperdine","Pittsburgh","Portland","Portland State","Prairie View A&M",
      "Princeton","Providence","Purdue","Radford","Rhode Island","Rice","Richmond",
      "Rider","Robert Morris","Rutgers","Sacramento State","Saint Francis",
      "Saint Joseph's","Saint Louis","Saint Mary's","Saint Peter's","Sam Houston State",
      "Samford","San Diego","San Diego State","San Francisco","San Jose State",
      "Seattle U","Seton Hall","Siena","SMU","South Alabama","South Carolina",
      "South Carolina State","South Dakota","South Dakota State","South Florida",
      "Southeast Missouri State","Southeastern Louisiana","Southern","Southern Illinois",
      "Southern Mississippi","Southern Utah","St. Bonaventure","Stanford",
      "Stephen F. Austin","Stetson","Syracuse","TCU","Temple","Tennessee",
      "Tennessee State","Tennessee Tech","Texas","Texas A&M","Texas Southern",
      "Texas State","Texas Tech","The Citadel","Toledo","Towson","Troy",
      "Tulane","Tulsa","UAB","UC Davis","UC Irvine","UC Riverside","UC San Diego",
      "UCF","UCLA","UMBC","UMass Lowell","UNC Asheville","UNC Greensboro",
      "UNC Wilmington","UNLV","USC","UT Arlington","UT Martin","Utah",
      "Utah State","Utah Valley","UTEP","UTSA","Valparaiso","Vanderbilt","Vermont",
      "Villanova","Virginia","Virginia Commonwealth","Virginia Military Institute",
      "Virginia Tech","Wagner","Wake Forest","Washington","Washington State",
      "Weber State","West Virginia","Western Carolina","Western Illinois",
      "Western Kentucky","Western Michigan","Wichita State","William & Mary",
      "Winthrop","Wisconsin","Wisconsin-Green Bay","Wisconsin-Milwaukee","Wofford",
      "Wright State","Wyoming","Xavier","Yale","Youngstown State"
    ],
    "NCAA D2": [
      "Adelphi","Alabama in Huntsville","Albany State","American International",
      "Anderson","Angelo State","Assumption","Augustana","Barry","Bellarmine",
      "Bemidji State","Bentley","Black Hills State","Bloomsburg","Bowie State",
      "California Baptist","Cal State Bakersfield","Cal State LA","Cameron",
      "Carson-Newman","Catawba","Central Missouri","Colorado Mesa","Colorado Mines",
      "Columbus State","Concordia Irvine","Concordia St. Paul","Delta State",
      "Dominican","Drury","East Stroudsburg","Eastern New Mexico","Emporia State",
      "Fairmont State","Fayetteville State","Ferris State","Findlay","Florida Southern",
      "Florida Tech","Fort Hays State","Francis Marion","Gannon","Grand Canyon",
      "Grand Valley State","Hawaii Pacific","Henderson State","Hillsdale",
      "Holy Family","Indianapolis","Le Moyne","Lenoir-Rhyne","Lewis","Lock Haven",
      "Lynn","Mercyhurst","Michigan Tech","Midwestern State","Minnesota Duluth",
      "Minnesota State Mankato","Missouri Southern","Missouri Western","Molloy",
      "Nebraska-Kearney","New Haven","North Alabama","North Greenville",
      "Northeastern State","Northern Michigan","Northern State","Northwest Missouri State",
      "Northwood","Nova Southeastern","Ohio Dominican","Oklahoma Christian",
      "Palm Beach Atlantic","Pittsburg State","Queens","Quincy","Regis",
      "Rockhurst","Rollins","St. Cloud State","St. Leo","Tarleton State",
      "Texas A&M Commerce","Tiffin","Truman State","Tusculum","Tuskegee",
      "Wayne State","West Alabama","West Chester","West Florida","West Georgia",
      "West Liberty","West Texas A&M","Wingate","Winona State"
    ]
  },

  "Basketball - Women": {
    "NCAA D1": [
      "Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor","California",
      "Clemson","Colorado","Connecticut","Duke","Florida","Florida State",
      "Georgia","Georgia Tech","Houston","Illinois","Indiana","Iowa","Iowa State",
      "Kansas","Kansas State","Kentucky","LSU","Louisville","Maryland",
      "Miami","Michigan","Michigan State","Minnesota","Mississippi State",
      "Missouri","Nebraska","North Carolina","North Carolina State","Northwestern",
      "Notre Dame","Ohio State","Oklahoma","Oklahoma State","Ole Miss","Oregon",
      "Oregon State","Penn State","Purdue","Rutgers","South Carolina",
      "South Florida","Stanford","Syracuse","TCU","Tennessee","Texas",
      "Texas A&M","Texas Tech","UCLA","USC","Utah","Vanderbilt","Virginia",
      "Virginia Tech","Wake Forest","Washington","Washington State","West Virginia",
      "Wisconsin","UConn"
    ]
  },

  // ─── TRACK & FIELD ────────────────────────────────────────────────────────
  "Track & Field - Men": {
    "NCAA D1": [
      "Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor",
      "Boston University","BYU","California","Clemson","Colorado","Duke",
      "Florida","Florida State","Fordham","Georgetown","Georgia","Georgia Tech",
      "Harvard","Houston","Illinois","Indiana","Iowa","Iowa State",
      "Kansas","Kansas State","Kentucky","LSU","Maryland","Michigan",
      "Michigan State","Minnesota","Missouri","Nebraska","North Carolina",
      "North Carolina State","Northwestern","Notre Dame","Ohio State","Oklahoma",
      "Ole Miss","Oregon","Oregon State","Penn State","Princeton","Purdue",
      "Rice","Rutgers","South Carolina","South Florida","Stanford","Syracuse",
      "TCU","Tennessee","Texas","Texas A&M","Texas Tech","UCLA","USC",
      "Utah","Vanderbilt","Virginia","Virginia Tech","Wake Forest","Washington",
      "Washington State","West Virginia","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "Abilene Christian","Adam State","Alabama in Huntsville","Angelo State",
      "Augustana","Cal Poly Pomona","Cal State LA","Carson-Newman","Central Missouri",
      "Chico State","Colorado Mines","Colorado State-Pueblo","Concordia St. Paul",
      "Drury","Emporia State","Ferris State","Fort Hays State","Grand Valley State",
      "Henderson State","Indiana PA","Kutztown","Lindenwood","Lincoln Memorial",
      "Midwestern State","Minnesota Duluth","Minnesota State Mankato",
      "Missouri Southern","Nebraska-Kearney","Newman","North Alabama",
      "Northern Michigan","Northern State","Northwest Missouri State","Northwood",
      "Pittsburg State","Regis","St. Cloud State","Shippensburg",
      "Slippery Rock","South Carolina Aiken","Southwest Baptist",
      "Southwest Minnesota State","Tarleton State","Texas A&M Commerce",
      "Tiffin","Truman State","Wayne State","West Chester","West Texas A&M",
      "Western Oregon","Winona State"
    ],
    "NCAA D3": [
      "Allegheny","Amherst","Bates","Bowdoin","Brandeis","Calvin","Carnegie Mellon",
      "Case Western Reserve","Christopher Newport","Colby","Connecticut College",
      "DePauw","Dickinson","Emory","Franklin & Marshall","Gettysburg",
      "Gustavus Adolphus","Hamilton","Haverford","Illinois Wesleyan",
      "Ithaca","John Carroll","Johns Hopkins","Kalamazoo","Kenyon",
      "Lawrence","Middlebury","MIT","Mount Union","Muhlenberg","Nebraska Wesleyan",
      "North Central","North Park","Ohio Wesleyan","Pomona-Pitzer","Rowan",
      "St. Lawrence","St. Olaf","St. Thomas","Swarthmore","Tufts","Union",
      "Wartburg","Washington","Williams","Wisconsin-La Crosse","Wisconsin-Oshkosh",
      "Wisconsin-Stevens Point","Wittenberg"
    ],
    "NAIA": [
      "Aquinas","Baker","Bethel","Biola","Bryan","Carroll","College of Idaho",
      "Concordia Ann Arbor","Cornerstone","Cumberland","Doane","Dordt",
      "Embry-Riddle","Friends","Georgetown College","Grand View","Hastings",
      "Indiana Wesleyan","John Brown","Kansas Wesleyan","Keiser","Lewis-Clark State",
      "Lindenwood","Madonna","Malone","Mary Hardin-Baylor","MidAmerica Nazarene",
      "Midland","Missouri Baptist","Montana Western","Morningside",
      "Mount Vernon Nazarene","Northwestern","Oklahoma Baptist","Oklahoma City",
      "Olivet Nazarene","Ottawa","Point Loma Nazarene","Reinhardt",
      "Rocky Mountain","Saint Francis","Siena Heights","Southern Nazarene",
      "Spring Arbor","St. Ambrose","Sterling","Tabor","Taylor","Texas Wesleyan",
      "Union","Vanguard","Waldorf","Wayland Baptist","William Carey","William Jewell"
    ]
  },

  "Track & Field - Women": {
    "NCAA D1": [
      "Alabama","Arizona","Arizona State","Arkansas","Auburn","Baylor",
      "Boston University","BYU","California","Clemson","Colorado","Duke",
      "Florida","Florida State","Georgetown","Georgia","Georgia Tech",
      "Harvard","Houston","Illinois","Indiana","Iowa","Iowa State",
      "Kansas","Kansas State","Kentucky","LSU","Maryland","Michigan",
      "Michigan State","Minnesota","Missouri","Nebraska","North Carolina",
      "North Carolina State","Northwestern","Notre Dame","Ohio State","Oklahoma",
      "Ole Miss","Oregon","Oregon State","Penn State","Princeton","Purdue",
      "Rice","Rutgers","South Carolina","Stanford","Syracuse","TCU",
      "Tennessee","Texas","Texas A&M","Texas Tech","UCLA","USC","Utah",
      "Vanderbilt","Virginia","Virginia Tech","Wake Forest","Washington",
      "Washington State","West Virginia","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "Adam State","Alabama in Huntsville","Angelo State","Augustana",
      "Cal Poly Pomona","Cal State LA","Carson-Newman","Central Missouri",
      "Chico State","Colorado Mines","Colorado State-Pueblo","Concordia St. Paul",
      "Drury","Emporia State","Ferris State","Fort Hays State","Grand Valley State",
      "Henderson State","Indiana PA","Lindenwood","Lincoln Memorial",
      "Midwestern State","Minnesota Duluth","Minnesota State Mankato",
      "Missouri Southern","Nebraska-Kearney","Newman","North Alabama",
      "Northern Michigan","Northern State","Northwest Missouri State",
      "Pittsburg State","Regis","St. Cloud State","Shippensburg","Slippery Rock",
      "South Carolina Aiken","Southwest Baptist","Tarleton State",
      "Texas A&M Commerce","Tiffin","Truman State","Wayne State","West Chester",
      "West Texas A&M","Western Oregon","Winona State"
    ],
    "NCAA D3": [
      "Allegheny","Amherst","Bates","Bowdoin","Brandeis","Calvin","Carnegie Mellon",
      "Case Western Reserve","Christopher Newport","Colby","Connecticut College",
      "DePauw","Dickinson","Emory","Franklin & Marshall","Gettysburg",
      "Gustavus Adolphus","Hamilton","Haverford","Illinois Wesleyan",
      "Ithaca","Johns Hopkins","Kalamazoo","Kenyon","Lawrence","Middlebury",
      "MIT","Mount Union","Muhlenberg","Nebraska Wesleyan","North Central",
      "North Park","Ohio Wesleyan","Pomona-Pitzer","Rowan","Smith","St. Lawrence",
      "St. Olaf","St. Thomas","Swarthmore","Tufts","Union","Ursinus",
      "Vassar","Wartburg","Washington","Williams","Wisconsin-La Crosse",
      "Wisconsin-Oshkosh","Wisconsin-Stevens Point","Wittenberg"
    ]
  },

  // ─── SWIMMING ─────────────────────────────────────────────────────────────
  "Swimming - Men": {
    "NCAA D1": [
      "Alabama","Arizona","Arizona State","Auburn","BYU","California","Clemson",
      "Duke","Florida","Florida State","Georgia","Georgia Tech","Harvard","Illinois",
      "Indiana","Iowa","Kansas","Kentucky","Louisville","LSU","Michigan",
      "Minnesota","Missouri","NC State","North Carolina","Northwestern","Notre Dame",
      "Ohio State","Penn State","Princeton","Purdue","Stanford","Tennessee",
      "Texas","Texas A&M","UCLA","USC","Utah","Vanderbilt","Virginia","Virginia Tech",
      "Washington","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "California Baptist","Columbus State","Delta State","Drury","Florida Southern",
      "Florida Tech","Grand Canyon","Indianapolis","Le Moyne","Nova Southeastern",
      "Queens","Rollins","St. Cloud State","UC San Diego","Upper Iowa"
    ],
    "NCAA D3": [
      "Amherst","Bates","Bowdoin","Brandeis","Calvin","Carnegie Mellon",
      "Case Western Reserve","Connecticut College","Denison","DePauw","Emory",
      "Hamilton","Johns Hopkins","Kenyon","MIT","Middlebury","Rowan","St. Lawrence",
      "Tufts","Union","Wabash","Washington","Williams","Wittenberg"
    ]
  },

  "Swimming - Women": {
    "NCAA D1": [
      "Alabama","Arizona","Arizona State","Auburn","BYU","California","Clemson",
      "Duke","Florida","Florida State","Georgia","Georgia Tech","Harvard","Illinois",
      "Indiana","Iowa","Kansas","Kentucky","Louisville","LSU","Michigan",
      "Minnesota","Missouri","NC State","North Carolina","Northwestern","Notre Dame",
      "Ohio State","Penn State","Princeton","Purdue","Stanford","Tennessee",
      "Texas","Texas A&M","UCLA","USC","Utah","Vanderbilt","Virginia","Virginia Tech",
      "Washington","Wisconsin","Yale"
    ],
    "NCAA D2": [
      "California Baptist","Columbus State","Delta State","Drury","Florida Southern",
      "Florida Tech","Grand Canyon","Indianapolis","Le Moyne","Nova Southeastern",
      "Queens","Rollins","UC San Diego","Upper Iowa"
    ],
    "NCAA D3": [
      "Amherst","Bates","Bowdoin","Brandeis","Calvin","Carnegie Mellon",
      "Case Western Reserve","Connecticut College","Denison","DePauw","Emory",
      "Hamilton","Johns Hopkins","Kenyon","MIT","Middlebury","Rowan","St. Lawrence",
      "Tufts","Union","Washington","Williams","Wittenberg"
    ]
  },
};

// Helper functions
export const getSportPrograms = (sport, gender, division) => {
  const key = `${sport} - ${gender}`;
  if (!SPORTS_PROGRAMS[key]) return [];
  if (!division) {
    return Object.entries(SPORTS_PROGRAMS[key]).flatMap(([div, unis]) =>
      unis.map(u => ({ name: u, division: div }))
    );
  }
  return (SPORTS_PROGRAMS[key][division] || []).map(u => ({ name: u, division }));
};

export const SPORT_OPTIONS = [
  "Soccer","Tennis","Golf","Volleyball","Baseball","Basketball","Track & Field","Swimming"
];

export const GENDER_OPTIONS = ["Men","Women"];

export const DIVISION_OPTIONS = ["NCAA D1","NCAA D2","NCAA D3","NAIA","NJCAA"];
